site_name: PalDefender Wiki
site_author: "Zvend"
site_description: "PalDefender (PalWorld Dedicated Server anticheat)"
site_url: https://ultimeit.github.io/PalDefender/
use_directory_urls: true
repo_url: https://github.com/Ultimeit/PalDefender
repo_name: Ultimeit/PalDefender

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  _snippets/**

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/LogoWiki.png
  favicon: assets/LogoWiki.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/shield-check-16
      tip: octicons/zap-16
      warning: octicons/alert-16
      danger: octicons/flame-16
  features:
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
        - locale: de
          name: Deutsch (German)
        - locale: zh
          name: 简体中文 (Chinese)
        - locale: ja
          name: 日本語 (Japanese)
        - locale: pt-BR
          name: Português do Brasil (Brazilian Portuguese)
          nav:
            - Início: index.md
            - Perguntas frequentes: FAQ.md
            - Recursos e status atual: Features.md
            - Instalação: Installation.md
            - Parcerias: Partnerships.md
            - Comandos: Commands/index.md
            - Tipos de arquivo:
                - Visão geral: FileTypes/index.md
                - Config.json: FileTypes/Config.md
                - Pals/ImportRules/*.json: FileTypes/PalImportRules.md
                - PalSummon.json: FileTypes/PalSummon.md
                - PalTemplate.json: FileTypes/PalTemplate.md
            - API REST:
                - Visão geral: RESTAPI/index.md
                - Autenticação e configuração: RESTAPI/authentication.md
                - Endpoints:
                    - Visão geral: RESTAPI/Endpoints/index.md
                    - GET /version: RESTAPI/Endpoints/version.md
                    - GET /players: RESTAPI/Endpoints/players.md
                    - GET /player: RESTAPI/Endpoints/player.md
                    - GET /pals: RESTAPI/Endpoints/pals.md
                    - GET /items: RESTAPI/Endpoints/items.md
                    - GET /techs: RESTAPI/Endpoints/techs.md
                    - GET /progression: RESTAPI/Endpoints/progression.md
                    - GET /guilds: RESTAPI/Endpoints/guilds.md
                    - GET /guild: RESTAPI/Endpoints/guild.md
                    - GET /banlist: RESTAPI/Endpoints/banlist.md
                    - POST /alert: RESTAPI/Endpoints/alert.md
                    - POST /broadcast: RESTAPI/Endpoints/broadcast.md
                    - POST /SendPlayerMessage: RESTAPI/Endpoints/send-player-message.md
                    - POST /ban: RESTAPI/Endpoints/ban.md
                    - POST /banip: RESTAPI/Endpoints/banip.md
                    - POST /unban: RESTAPI/Endpoints/unban.md
                    - POST /unbanip: RESTAPI/Endpoints/unbanip.md
                    - POST /kick: RESTAPI/Endpoints/kick.md
                    - POST /deletebase: RESTAPI/Endpoints/deletebase.md
                    - POST /give/items: RESTAPI/Endpoints/give-items.md
                    - POST /give/pals: RESTAPI/Endpoints/give-pals.md
                    - POST /give/paleggs: RESTAPI/Endpoints/give-paleggs.md
                    - POST /give/paltemplate: RESTAPI/Endpoints/give-paltemplate.md
                    - POST /give/progression: RESTAPI/Endpoints/give-progression.md
                    - POST /give: RESTAPI/Endpoints/give_deprecated.md
                    - POST /learntech: RESTAPI/Endpoints/learntech.md
                    - POST /forgettech: RESTAPI/Endpoints/forgettech.md
                    - POST /reload-config: RESTAPI/Endpoints/reload-config.md
                    - POST /summon/pal: RESTAPI/Endpoints/summon-pal.md
                    - POST /summon/npc: RESTAPI/Endpoints/summon-npc.md
                - Exemplos:
                    - Python: RESTAPI/Examples/Python.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ultimeit/PalDefender
      name: PalDefender on GitHub
