name: "Bug Report"
description: "Report a reproducible problem with PalDefender."
title: "[Bug]: "
labels:
  - "bug"
body:
  - type: dropdown
    id: version
    attributes:
      label: "PalDefender Version"
      description: "Which version of PalDefender are you running? Stable v1.9.x releases are currently supported."
      options:
        - "v1.9.1"
        - "v1.9.0"
        - "Older than v1.9.0 (unsupported)"
        - "Pre-release, beta, or custom build (unsupported)"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What happened?"
      description: Please provide every bit of information that you have.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: "Describe exactly how to reproduce the bug. For example, if a command is not working, include the command you entered."
      value: |
        1. ...
        2. ...
        3. See bug "..."
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop your screenshot here, or copy and paste it."
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted, so no need for backticks.
      render: bash
    validations:
      required: false
