name: "Bug Report"
description: Create a new issue for a bug.
title: "Your title"
labels: [
  "bug"
]
body:
  - type: dropdown
    id: version
    attributes:
      label: "PalDefender Version"
      description: What version of PalDefender are you running?
      multiple: true
      options:
        - v1.4.6
        - v1.4.5
        - v1.4.4
        - v1.4.3
        - v1.4.2
        - v1.4.0
        - v1.3.1
        - v1.3.0
        - v1.1.6
        - Older than v1.1.6
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What happened?"
      description: Please provide every bit of information that you have.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your bug. E.g.: It doesnt help us when you tell us a command is not working without providing the command you typed.
      value: |
        1. ...
        2. ...
        3. See bug "..."
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: just drag & drop your screenshot or copy & paste it.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted, so no need for backticks.
      render: bash
    validations:
      required: false
